apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-gov.fullname" . }}-secret
  labels:
    {{- include "ai-gov.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.database.host }}
  database-password: {{ .Values.config.database.password | b64enc }}
  {{- end }}
  {{- if .Values.config.gateway.adminToken }}
  admin-token: {{ .Values.config.gateway.adminToken | b64enc }}
  {{- end }}
  {{- if .Values.config.gateway.bootstrapAdminPassword }}
  bootstrap-admin-password: {{ .Values.config.gateway.bootstrapAdminPassword | b64enc }}
  {{- end }}
  {{- if .Values.config.gateway.secretKey }}
  secret-key: {{ .Values.config.gateway.secretKey | b64enc }}
  {{- end }}
  {{- if .Values.config.redis.password }}
  redis-password: {{ .Values.config.redis.password | b64enc }}
  {{- end }}
  {{- if .Values.config.metrics.token }}
  metrics-token: {{ .Values.config.metrics.token | b64enc }}
  {{- end }}